### ISSUE TITLE
Option to not perform network check?

### ISSUE THREAD

**Issue by dwgeddes** [rtrouton/First_Boot_Package_Install_Generator#1]
I may be missing something, so I apologize in advance if I'm out of line, but it seems like there should be an option to remove the network check completely.

Even if you have a script or package that you will be deploying that requires a network connection, it seems to me that you should have the option to perform error checking as you'd like for that script/package, rather than having having it be part of your script.  By forcing a network check when it might not be necessary, the only real result is that it prohibits deploying an image offline, e.g. from an external hard drive.

I altered the app to remove the network check, and everything worked fine.  Either way, thanks for the useful app!

**Comment by deftdawg** [comment]
I'm pretty sure the reason for the network check is so packages with http references can install properly, but it's really counter productive for my use case as well (just installing munki-tools and a munki-client-config package) since I do my initial netinstall over wifi.   

The behaviour of self-destructing without installing after 60 minutes also doesn't make much sense to me, because I would think it results in have to either re-image the machine again or manually install everything - neither seems ideal.

@dwgeddes, any chance you could share your modified version?

**Comment by dwgeddes** [comment]
I'm willing to share it, but I don't know the best way to do that.  What I did wasn't too complicated.

1) Download/install the app, browse the package contents, and copy "installer_build_components.tgz" into a temporary directory somewhere.  Extract the contents of "installer_build_components.tgz"

2) Edit "private/user/firstbootpackageinstall_noswupdates.sh".  Comment out or delete lines 84-114 (the section that checks for a network connection)

3) Recompress that directory (e.g. "tar -cvzf installer_build_components.tgz installer_build_components")

4) Replace the "installer_build_components.tgz" file in the package contents with the one you just created.

5) When creating your first-boot package, select the option not to install updates.

**Comment by deftdawg** [comment]
@dwgeddes cheers, I didn't realize it was just tar'ed up inside the package.  I managed to modify it to do the same thing as yours.  Thanks :+1:
